# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: logchef-mcp

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GITHUB_ORG=mr-karan

before:
  hooks:
    - go mod tidy

builds:
  - binary: logchef-mcp
    main: ./cmd/logchef-mcp
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.version={{ .Tag }}" -X "main.commit={{ .ShortCommit }}" -X "main.date={{ .Date }}"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    formats:
      - tar.gz
    files:
      - README.md
      - LICENSE*

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:latest"
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description="Logchef MCP Server - Model Context Protocol server for Logchef"
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    dockerfile: Dockerfile.goreleaser

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).